/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-secondary-container": "#d9c8ff",
        "outline-variant": "#484847",
        tertiary: "#ffa3e9",
        background: "#0e0e0e",
        error: "#ff6e84",
        surface: "#0e0e0e",
        "primary-container": "#859aff",
        "error-container": "#a70138",
        "inverse-on-surface": "#565555",
        "secondary-dim": "#8455ef",
        "on-surface": "#ffffff",
        "surface-container-lowest": "#000000",
        "surface-bright": "#2c2c2c",
        "surface-dim": "#0e0e0e",
        "primary-fixed": "#859aff",
        "tertiary-fixed-dim": "#e883d2",
        secondary: "#ac8aff",
        "surface-variant": "#262626",
        "on-primary-fixed-variant": "#00207e",
        "on-tertiary-container": "#5f0656",
        "on-primary-container": "#001867",
        "primary-fixed-dim": "#718bff",
        "secondary-fixed": "#dac9ff",
        "surface-tint": "#97a9ff",
        "on-background": "#ffffff",
        "on-primary-fixed": "#000000",
        "on-secondary-fixed": "#40009b",
        "primary-dim": "#3e65ff",
        "on-tertiary": "#6c1561",
        "inverse-primary": "#134af1",
        "on-secondary-fixed-variant": "#5f28c8",
        "on-primary": "#002283",
        "surface-container-high": "#20201f",
        "surface-container-low": "#131313",
        "on-secondary": "#280067",
        "tertiary-fixed": "#f790e0",
        "error-dim": "#d73357",
        "on-error": "#490013",
        "secondary-container": "#5516be",
        primary: "#97a9ff",
        "inverse-surface": "#fcf9f8",
        "on-tertiary-fixed-variant": "#6a1460",
        "secondary-fixed-dim": "#ceb9ff",
        "surface-container": "#1a1a1a",
        "on-surface-variant": "#adaaaa",
        "tertiary-container": "#f790e0",
        "surface-container-highest": "#262626",
        "on-error-container": "#ffb2b9",
        "tertiary-dim": "#e883d2",
        outline: "#767575",
        "on-tertiary-fixed": "#380033",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["Space Grotesk", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
};
